INSERT INTO address(title, firstname, lastname, addressLine1, addressLine2, townCity, county, postcode)
VALUES ("Mr", "Joe", "Him", "6 George Street", null, "Leicester", "Leicestershire", "LE50 7NT"),
("Mr", "James", "Him", "4 Foundry Place", "High Street Fordington", "Dorchester", "Dorset", "DT1 1LX"),
("Mrs", "Jennine", "Betz", "11 Highfield Road", null, "Manchester", "Greater Manchester", "M59 9JG"),
("Miss", "Tess", "Verse", "56 Albert Road", null, "Tunbridge Wells", "Kent", "TN18 6RT"),
("Miss", "Paula", "Every" ,"657 Washwood Heath Rd", null, "Birmingham", "West Midland", "B8 2HJ"),
("Miss", "Yulanda", "Revelez", "Flat 2", "Hilary Court", "Lichfield Grove", "London", "N3 2JG"),
("Miss", "Gennie", "Diestel", "Corner Cottage", "10 St Barbaras Road", "Corsham", "Wiltshire", "SN13 9NU"),
("Dr", "Ray", "Heimbuch", "Manor Cottage", "School Road", "Aston Somerville", "Gloucester", "WR12 7JD"),
("Mrs", "June", "Zero", "4 Harbord Terrace", null, "Liverpool", "Merseyside", "L22 8QQ"),
("Master", "Archie", "Mensik", "102 Haslemere", null, "Whiston", "Merseyside", "L35 3TW"),
("Mr", "Yong", "Horde", "97 Lower Beeches Road", null, "Birmingham ", "West Midlands", "B31 5FL"),
("Dr", "Laurette", "Leather", "2 Grimson Close", null, "Sully", "South Glamorgan", "CF64 5UX"),
("Miss", "Teresa", "Guberman", "Rose Bungalow", "Kitwood Lane", "Ropley", "Hampshire", "SO24 0DB"),
("Ms", "Louise", "Soft", "2 Ferry Farm Drive", null, "Ropley", "Staffordshire", "ST17 4JE"),
("Ms", "Katie", "Maschino", "24 Aldersmead Rd", null, "Stafford", "Greater London", "BR3 1NA"),
("Ms", "Milly", "Cap", "341 Canford Lane", null, "Bristol", "Hampshire", "SO24 0DB"),
("Master", "Craig", "Book", "27 St Mary's Close", "Trimley St. Mary", "Felixstowe", "Suffolk", "IP11 0TY");